### ISSUE TITLE
OrcaWave: add licensed end-to-end acceptance test for arbitrary mesh workflow

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/digitalmodel#610]
## Problem

There is smoke-test coverage for known OrcaWave inputs, but the future workflow needs proof that an arbitrary mesh-driven DigitalModel spec can run end-to-end on a licensed host.

## Required work

Add an acceptance test, intended for the licensed Windows environment, that exercises:

1. Mesh fixture + `spec.yml`
2. DigitalModel OrcaWave input generation/package preparation
3. OrcFxAPI `Diffraction(...).Calculate()`
4. Save `.owr`
5. Export `.xlsx`
6. Extract/report enough results to verify the output is usable

## Acceptance criteria

- [ ] Test runs on the licensed OrcFxAPI environment and exits 0.
- [ ] Test fixture starts from a mesh/spec pair managed in the repo.
- [ ] Generated `.yml`, copied/converted mesh, `.owr`, and `.xlsx` paths are recorded.
- [ ] Test verifies non-empty frequencies, headings, hydrostatic data, and at least one RAO/result array.
- [ ] Linux/CI path skips cleanly when OrcFxAPI is unavailable.

## References

- Related completed issue: #468
- `tests/solver/smoke_test.py`
- `src/digitalmodel/hydrodynamics/diffraction/orcawave_runner.py`
- `src/digitalmodel/hydrodynamics/diffraction/solver/report_extractors.py`

**Comment by vamseeachanta** [comment]
Plan progressed to `status:plan-review` in commit `2fee33fb`.

Plan: https://github.com/vamseeachanta/digitalmodel/blob/main/docs/plans/2026-05-15-issue-610-orcawave-arbitrary-mesh-acceptance-test.md

Review artifacts:
- Claude: https://github.com/vamseeachanta/digitalmodel/blob/main/scripts/review/results/2026-05-15-plan-610-claude.md
- Codex: https://github.com/vamseeachanta/digitalmodel/blob/main/scripts/review/results/2026-05-15-plan-610-codex.md
- Gemini: https://github.com/vamseeachanta/digitalmodel/blob/main/scripts/review/results/2026-05-15-plan-610-gemini.md

Final review state: Claude `UNAVAILABLE`, Codex `UNAVAILABLE`, Gemini `UNAVAILABLE` on the final rerun due provider quota/usage exhaustion. The prior fresh Gemini MAJOR findings were patched: collection-safe future-dependency imports, unlicensed harness mocks/static JSON, deterministic proof-marker `host`/`command`, and SHA-256 for the generated `.yml`. Implementation remains gated by user approval and the upstream dependencies named in the plan.

**Comment by vamseeachanta** [comment]
## 📊 Completeness assessment — 25%

Adversarial audit against `main@998abd24`. Full scorecard: `docs/domains/orcawave/2026-05-27-issue-completeness-scorecard.html`.

| Criterion | Status |
|---|---|
| Runs on licensed OrcFxAPI, exits 0 | 🟡 PARTIAL (only the pre-existing #468-style path) |
| Fixture starts from a **mesh/spec pair** → generated inputs | ❌ MISSING — L01 loads a pre-built committed `.yml` (`smoke_test.py:37-44`), never runs `OrcaWaveBackend`/`OrcaWaveRunner` |
| Generated `.yml`/mesh/`.owr`/`.xlsx` recorded | 🟡 PARTIAL (no generated `.yml`/mesh) |
| Verifies freqs/headings/hydrostatics + RAO array | 🟡 PARTIAL (L00 checks freq_count only) |
| Linux/CI skips cleanly | 🟡 PARTIAL — wrappers `test_l00/l01_smoke` lack `skipif`; would error on `import OrcFxAPI`, not skip |

**Biggest gap:** no test that *generates* inputs from a mesh+spec fixture (the arbitrary-mesh path, distinct from #468), plus missing Linux skip guard.

**Comment by vamseeachanta** [comment]
Licensed E2E acceptance test built in #631 (Thread A, dev-primary).

- Drives the full DigitalModel -> OrcaWave chain from a repo-managed mesh+spec pair (`tests/hydrodynamics/diffraction/fixtures/acceptance_610/`: `unit_box.gdf` + `spec.yml`).
- Test: `tests/solver/test_licensed_e2e_arbitrary_mesh.py` — runner -> `Diffraction.Calculate()` -> `.owr`/`.xlsx`, asserts non-empty freqs/headings/hydrostatics, >=1 RAO array, and a non-SKIPPED auto-validation verdict (#625).
- Skip confirmation on ace-linux-1 (no license): **6 skipped**, not failed/errored. Lazy OrcFxAPI import; collection never raises.
- licensed-win-1 run discharges #610 acceptance + #628 live-attrs-after-Calculate() debt.

Filed as **Refs** (not Closes): the #625 runtime does not yet populate `RunResult.xlsx_path` (reserved, locked decision D2), so the test exports the `.xlsx` from the `.owr` itself. Flagging for maintainer confirmation before close.

**Comment by vamseeachanta** [comment]
## 📍 Status — test merged, licensed run pending (issue stays OPEN)

PR #631 (`test(diffraction): #610 licensed E2E acceptance`) merged the acceptance test + repo fixtures (`tests/solver/test_licensed_e2e_arbitrary_mesh.py`, `tests/.../fixtures/acceptance_610/{spec.yml,unit_box.gdf}`). Acceptance status:

| Criterion | Status |
|---|---|
| Test runs on licensed OrcFxAPI env, exits 0 | ⏳ **pending** `licensed-win-1` run (verification debt) |
| Fixture from repo-managed mesh/spec pair | ✅ done |
| `.yml` / mesh / `.owr` / `.xlsx` paths recorded | ⚠️ `.owr` yes; **`.xlsx` export deferred per locked decision D2** |
| Verifies non-empty freqs / headings / hydrostatic / ≥1 RAO array | ⏳ assertions **coded**, fire only on the licensed host |
| Linux/CI skips cleanly when OrcFxAPI unavailable | ✅ done (module-level `skipif` → SKIPPED on dev-primary, verified) |

**Why this stays open:** criteria #1 and #4 require an actual run on `machine:licensed-win-1` — they cannot be exercised on `dev-primary` (no `OrcFxAPI`). Closing now would mark unverified-as-verified.

**Discharge path:** on the licensed host (`set PYTHONPATH=src` · `uv run python -m pytest tests/solver/test_licensed_e2e_arbitrary_mesh.py -v`) — a green run also discharges the #628 live-`Diffraction`-attrs-after-`Calculate()` verification debt (the `.owr LoadResults` fallback keeps it green either way). Close on that evidence.

**Note for future sessions:** even a green licensed run leaves criterion #3/#5 (`.xlsx` export) unmet until xlsx *production* is wired — that leg is deferred by D2, tracked under epic #622. Two separate gates, not one.

(Not touching the `status:*` label per the epic conventions.)

**Comment by vamseeachanta** [comment]
## Pre-licensed dry-run rehearsal — GREEN (ace-linux-2, 2026-06-12)

To de-risk the licensed-win-1 session, the acceptance fixture was rehearsed through the real CLI path on an unlicensed host:

```
uv run diffraction run-orcawave tests/hydrodynamics/diffraction/fixtures/acceptance_610/spec.yml --dry-run -o /tmp/orcawave_rehearsal_610
```

Result: `[DRY_RUN]`, exit 0. Package produced:
- `Acceptance610_UnitBox.yml` (solver input) with **relative** `BodyMeshFileName: unit_box.gdf`
- `unit_box.gdf` copied alongside (1 mesh copied)
- 9 modular section files under `modular/`
- Validation correctly `SKIPPED` (no results in dry-run)

So the spec → convert → package leg is verified portable; the licensed run should only exercise the `Calculate()` → `.owr` → OutputValidator leg, including discharging the unverified live-attrs assumption from #628.

Two gotchas for whoever runs this on licensed-win-1:
1. Invoke via the console script `uv run diffraction run-orcawave ...` — `uv run python -m digitalmodel diffraction ...` crashes in the legacy engine (filed as #713).
2. A canonical runnable example mirroring this fixture is being added under `examples/hydrodynamics/diffraction/` (#712); consider confirming it in the same licensed session.

**Comment by vamseeachanta** [comment]
## Licensed acceptance run attempted: FAILED, do not close

Ran the #610 licensed gate on the Windows checkout at `C:\ws\digitalmodel` after syncing `main`.

**Commit:** `1af57466065af09389ab70bcc4e90dad4561a382`

**Environment proof**

- `OrcaWave`: `C:\Program Files (x86)\Orcina\OrcaFlex\11.6\OrcaWave.exe`
- `OrcFxAPI` import path: `C:\Program Files (x86)\Orcina\OrcaFlex\11.6\OrcFxAPI\Python\OrcFxAPI.py`
- Requested command `python -c "import OrcFxAPI; print(OrcFxAPI.Version())"` does **not** work on this installed 11.6 API shim because `Version` is not exposed: `AttributeError: module 'OrcFxAPI' has no attribute 'Version'`
- Fallback version proof: `OrcFxAPI.DLLVersion()` -> `11.6c`

To make the repo path importable in this agent Python, I used:

```powershell
$env:PYTHONPATH='C:\ws\assetutilities\src;C:\Program Files (x86)\Orcina\OrcaFlex\11.6\OrcFxAPI\Python;src'
$env:PATH='C:\Program Files (x86)\Orcina\OrcaFlex\11.6;' + $env:PATH
```

### Formal #610 pytest gate

Command:

```powershell
python -m pytest tests/solver/test_licensed_e2e_arbitrary_mesh.py -v
```

Result summary:

```text
collected 6 items
6 failed in 4.20s
PYTEST_EXIT_CODE=1
PYTEST_WALL_CLOCK=00:00:05.9007756
```

Primary failure:

```text
Expected COMPLETED, got RunStatus.FAILED:
Error code: 63
Operation not available (Unrecognised header: 'C:\Users\vamseea\AppData\Local\Temp\pytest-of-vamseea\pytest-17\acceptance_6100\unit_box.gdf', line 2)
```

No `.owr`, `_data.dat`, or `.xlsx` was produced. `validation_verdict` remained `SKIPPED` with issue `OrcFxAPI calculation failed; no diffraction results to validate`. The #628 live-attrs branch was not reached because `Calculate()` failed before result extraction.

Generated acceptance input excerpt:

```yaml
BodyName: Acceptance610_UnitBox
BodyMeshFileName: unit_box.gdf
BodyMeshFormat: Wamit gdf
BodyMeshLengthUnits: m
BodyMeshSymmetry: xz plane
```

Copied fixture mesh header that OrcFxAPI rejected:

```text
# Sample box mesh in WAMIT GDF format
# A simple unit box with 5 wetted panels (bottom + 4 sides, open top at waterline)
# Generated for BEMRosetta module testing
1.0  9.81
0  0
5
```

### Canonical shipped example

Command:

```powershell
diffraction run-orcawave examples/hydrodynamics/diffraction/unit_box_rao/spec.yml -o output_610\
```

Run summary block:

```text
[FAILED]
  Input file : output_610\UnitBoxRAO.yml
  Output dir : output_610
  Modular    : 9 section files
  Mesh files : 1 copied
  [QUALITY] Body 'UnitBoxRAO' mesh ('unit_box.gdf') quality WARNING: Mesh is not watertight
  [QUALITY] Body 'UnitBoxRAO' mesh ('unit_box.gdf') quality WARNING: 4 open edges found (not watertight)
  [QUALITY] Body 'UnitBoxRAO' mesh ('unit_box.gdf') quality WARNING: Panel count (5) is very low - results may be inaccurate
  [QUALITY] Body 'UnitBoxRAO' mesh ('unit_box.gdf') quality WARNING: Aspect ratio range: [1.00, 1.00]
  [QUALITY] Body 'UnitBoxRAO' mesh ('unit_box.gdf') quality WARNING: Element size range: [1.000, 1.000] m (mean=1.000 m)
  Duration   : 0.55s
  XLSX       : (deferred)
  Report     : (none)
  Validation : SKIPPED
      - OrcFxAPI calculation failed; no diffraction results to validate
  Error      :
Error code: 63
Operation not available (Unrecognised header: 'C:\ws\digitalmodel\output_610\unit_box.gdf', line 2)
RUN_ORCAWAVE_EXIT_CODE=0
RUN_ORCAWAVE_WALL_CLOCK=00:00:02.8102564
```

Artifact state in `output_610\`:

```text
UnitBoxRAO.yml             3295 bytes
unit_box.gdf                798 bytes
mesh_quality_report.json   1512 bytes
modular\master.yml         3295 bytes
modular section files      generated
.owr                       absent
_data.dat                  absent
.xlsx                      absent (expected deferred only if solve otherwise succeeds)
```

Important extra observation: the console command reported `[FAILED]` but exited with code `0`.

### Failure localization

Per the failure-handling instructions, I ran the known smoke suite:

```powershell
python -m pytest tests/solver/smoke_test.py -v
```

Summary:

```text
tests/solver/smoke_test.py::test_l00_smoke PASSED
tests/solver/smoke_test.py::test_l01_smoke FAILED
1 failed, 1 passed in 43.08s
SMOKE_EXIT_CODE=1
SMOKE_WALL_CLOCK=00:00:44.9406804
```

L00 passed, proving this host can import OrcFxAPI, calculate a simple `.owd`, save `.owr`, and export `.xlsx`.

L01 failed with the known #714 180-case pattern:

```text
Error code: 63
Operation not available

Out of memory

There was not enough available memory to perform the calculation - please try reducing the thread count.
```

That resembles the documented `docs/domains/orcawave/examples/L01_default_vessel/API_EXECUTION_SUMMARY.md` 180-case benchmark issue. The #610 unit-box failure does **not** resemble the timeout/OOM pattern; it fails immediately while loading/parsing the generated/copy-packaged `unit_box.gdf` because OrcFxAPI rejects the comment header.

### Acceptance criteria status

- Test runs on licensed OrcFxAPI environment and exits 0: **not met** (`6 failed`, exit 1).
- Fixture starts from repo-managed mesh/spec pair: **met as packaging/input**, but the fixture mesh is not accepted by OrcFxAPI as shipped.
- Generated `.yml`, copied mesh, `.owr`, `.xlsx` paths recorded: **partially met** for generated `.yml` and copied mesh only; `.owr`/`.xlsx` absent because solve failed.
- Verifies non-empty frequencies, headings, hydrostatic data, and RAO/result array: **not met**; no results produced.
- Linux/CI skip behavior: **not evaluated in this licensed run**.

#610 should remain open. The next defect to fix is the OrcaWave-compatible packaging/fixture mesh format for `unit_box.gdf` (likely strip/convert the comment-prefixed GDF header before passing it to OrcFxAPI), plus the CLI should probably return non-zero when `run-orcawave` reports `[FAILED]`.

**Comment by vamseeachanta** [comment]
## Failure evidence hand-verified — root cause fixed in PR #741

The 2026-06-13 licensed-run report checks out on independent verification against the source:

- **Root cause confirmed**: `unit_box.gdf` carried three leading `#` comment lines; WAMIT GDF permits exactly one header line, so OrcaWave reads line 2 expecting `ULEN GRAV` and rejects with `Unrecognised header ... line 2`. BEMRosetta's reader skips extra comments (`gdf_handler.py:74-79`) — masking this on every unlicensed host — while its **writer** emits valid single-header files, so #606-converted meshes were never at risk. Only hand-authored fixtures were malformed (repo sweep found five copies; all fixed).
- **Environment exoneration confirmed**: L00 smoke passing proves OrcFxAPI + license + save/export all work on that host. The L01 OOM is the known, separately-tracked #714 pattern.
- **CLI exit-code defect confirmed and fixed**: `run-orcawave` reported `[FAILED]` with exit 0; both run commands now exit 1 on a FAILED result.

PR #741 (issue #740) additionally adds a **blocking GDF structural preflight** to the quality gate — line 2 two floats / line 3 two ints / line 4 int — so this class of solver-certain rejection fails at dry-run/package time on any host rather than burning a licensed session.

**Next licensed attempt** (after #741 merges, sync main first):
1. `diffraction orcawave-doctor --require-solver` (env preflight)
2. `python -m pytest tests/solver/test_licensed_e2e_arbitrary_mesh.py -v` — the fixture mesh now parses under OrcaWave's strict reader
3. `diffraction run-orcawave examples/hydrodynamics/diffraction/unit_box_rao/spec.yml -o output_610\` — a FAILED run now exits non-zero

This issue remains the open acceptance gate.
